apiVersion: apps/v1
kind: Deployment
metadata:
  name: pendo-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pendo-backend
  template:
    metadata:
      labels:
        app: pendo-backend
    spec:
      containers:
      - name: backend
        image: pendo/backend:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: pendo-secrets
              key: database-url
        - name: REDIS_HOST
          value: redis
        - name: ENVIRONMENT
          value: production
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: media
          mountPath: /app/media
        - name: config
          mountPath: /app/config
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media-pvc
      - name: config
        configMap:
          name: pendo-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pendo-celery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pendo-celery
  template:
    metadata:
      labels:
        app: pendo-celery
    spec:
      containers:
      - name: celery
        image: pendo/backend:latest
        command: ["celery", "-A", "app.core.celery_app", "worker", "-l", "info"]
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: pendo-secrets
              key: database-url
        - name: REDIS_HOST
          value: redis
        - name: ENVIRONMENT
          value: production
        volumeMounts:
        - name: media
          mountPath: /app/media
        - name: config
          mountPath: /app/config
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media-pvc
      - name: config
        configMap:
          name: pendo-config

---
apiVersion: v1
kind: Service
metadata:
  name: pendo-backend
spec:
  selector:
    app: pendo-backend
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
